### ISSUE TITLE
希望最后别搞的国内上不了github。

### ISSUE THREAD

**Issue by liaoweijun** [monyhar/monyhar#11]

**Comment by YexuanXiao** [comment]
什么时候能上了，今年很多地区都瘫了

**Comment by liaoweijun** [comment]
> 什么时候能上了，今年很多地区都瘫了

我这里一直可以上。

**Comment by YexuanXiao** [comment]
> > 什么时候能上了，今年很多地区都瘫了
> 
> 我这里一直可以上。

坐标大连和哈尔滨，访问速度接近无穷。

**Comment by dingchaoSYY** [comment]
跪久了，站不起来了，蛤蛤蛤

**Comment by dingchaoSYY** [comment]
https://program-think.blogspot.com/2019/10/70th-anniversary-of-PRC.html
建议@liaoweijun 大脑升级

**Comment by liaoweijun** [comment]
> https://program-think.blogspot.com/2019/10/70th-anniversary-of-PRC.html
> 建议@liaoweijun 大脑升级

沙雕

**Comment by liaoweijun** [comment]
> 跪久了，站不起来了，蛤蛤蛤

是你跪。我不必要，希望你懂我说的什么意思。

**Comment by PickaxeHit** [comment]
新疆已经访问不了了

**Comment by MrQianitsme** [comment]
主要还是限速而已

**Comment by TooYoungTooSimp** [comment]
几个月前就上不了了，您还真是多虑了。

**Comment by yjhenan** [comment]
以前就封过，只要国内it产业还要，就得解封
