### ISSUE TITLE
是不是觉得自己很幽默

### ISSUE THREAD

**Issue by Difficulty-in-naming** [monyhar/monyhar#145]
觉得鸿蒙不好就去建设他.不支持也别到处冷嘲热讽.哗众取宠.自己心里有数就行.

**Comment by TooYoungTooSimp** [comment]
如果你觉得华为不好，你就去建设它；如果你觉得华为不好，你就去考迫真博士去入职华为；如果你觉得华为海军没素质，就从你开始做一个高素质的华为海军；如果你觉得海军愚昧无知，就从你开始学习并解决掉身边不是海军的人，它有缺点，我们一起修正，而不是一昧的谩骂，抱怨，逃离。

如果你觉得黑煤矿不好，你就去建设黑煤矿；如果你觉得黑煤矿不好，你就去签临时合同加入黑煤矿；如果你觉得那些觉得黑煤矿增加GDP的人没良心，就从你开始做一个有良心的觉得黑煤矿增加了GDP的人。黑煤矿有缺点，我们一起修正。

**Comment by Difficulty-in-naming** [comment]
我认为这完全是两个问题.华为海军那种完全是炒作把黑的说成白的.这种我们可以大力谴责.黑煤矿这种迫害人权的行为我们应该是大力揭露他
但是鸿蒙作为软件不存在任何问题.安卓本事就是大家的.是开源的.而且鸿蒙不完全是安卓.我们还是能看到华为是想努力把鸿蒙做好的.你们不喜欢没能力不去建设也没问题.但是不要像个小丑一样去到处说.

**Comment by Difficulty-in-naming** [comment]
阴阳怪气.觉得自己好像众人皆醉我独醒.
或者跟风看了几篇华为鸿蒙的文章仿佛自己大彻大悟一般就开始到处被别人当枪使
非蠢即坏

**Comment by sakimizumi** [comment]
扎布多德嘞

**Comment by TooYoungTooSimp** [comment]
这个repo是为了打破外国的浏览器垄断，作为软件不存在任何问题。你不喜欢没能力不去建设也没问题.但是不要像个小丑一样在issues里面说.觉得自己好像众人皆醉我独醒.非蠢即坏。
🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by Difficulty-in-naming** [comment]
代码在哪.我没看到.这个仓库就是把整个Chrome的代码放到了一个文件夹中.甚至一点仓库创建者的提交都没有.你觉得这叫软件？这叫打破垄断？这个仓库就是你们这帮媚外党的集中营

**Comment by rhjdvsgsgks** [comment]
> 代码在哪.我没看到.这个仓库就是把整个Chrome的代码放到了一个文件夹中.甚至一点仓库创建者的提交都没有.你觉得这叫软件？这叫打破垄断？这个仓库就是你们这帮媚外党的集中营

是你不懂开源，为什么非得有仓库创建者的提交？
这个仓库是你们这帮媚中党的集中营吧，对媚中党来说确实是集中营

**Comment by Difficulty-in-naming** [comment]
> > 代码在哪.我没看到.这个仓库就是把整个Chrome的代码放到了一个文件夹中.甚至一点仓库创建者的提交都没有.你觉得这叫软件？这叫打破垄断？这个仓库就是你们这帮媚外党的集中营
> 
> 是你不懂开源，为什么非得有仓库创建者的提交？
> 这个仓库是你们这帮媚中党的集中营吧，对媚中党来说确实是集中营

我身为中国人我媚中,我爱国.我不可耻.你崇洋媚外.你下贱.
还有我从头到尾没有说开源的问题.我指的是你100%拷贝创建人的代码没有自己的一点成分.还吹嘘是自己的软件.人家鸿蒙多少都改了60%70%,你哪怕改个变量名都行.

**Comment by rhjdvsgsgks** [comment]
> > > 代码在哪.我没看到.这个仓库就是把整个Chrome的代码放到了一个文件夹中.甚至一点仓库创建者的提交都没有.你觉得这叫软件？这叫打破垄断？这个仓库就是你们这帮媚外党的集中营
> > 
> > 
> > 是你不懂开源，为什么非得有仓库创建者的提交？
> > 这个仓库是你们这帮媚中党的集中营吧，对媚中党来说确实是集中营
> 
> 我身为中国人我媚中,我爱国.我不可耻.你崇洋媚外.你下贱.
> 还有我从头到尾没有说开源的问题.我指的是你100%拷贝创建人的代码没有自己的一点成分.还吹嘘是自己的软件.人家鸿蒙多少都改了60%70%,你哪怕改个变量名都行.

我可没说我媚外，你从哪看出来的？不会是不媚中就是媚外吧？
你从哪里看出来的“没有自己的一点成分”？最近几个commit都是上游的？鸿蒙改了60%70%你又是从哪看出来的？
