### ISSUE TITLE
有嘲讽华为的时间和精力，为什么不自己搞一套操作系统出来？？？？

### ISSUE THREAD

**Issue by LCG22** [monyhar/monyhar#164]

**Comment by shadow1163** [comment]
我觉得这是一个非常好的想法，基于chromium OS 的 monyhar OS应该安排到PPT里了。

**Comment by nocrizwang** [comment]
中国自主研发触动你哪根敏感的神经了？中国不能有自主研发浏览器？为什么唱衰国内浏览器？你收了美元还是日元？谁指使你来的？你是什么目的？你在暗示什么？

**Comment by LCG22** [comment]
> 中国自主研究触动你哪根敏感的神经了？中国不能有自主研究浏览器？你为什么收唱衰国内浏览器？你收了美元还是日元？谁指使你来的？你在暗示什么？ ？

笑死我了，现在的 AI 都这么差的吗？我哪里说到有关浏览器了？

**Comment by LCG22** [comment]
> 我觉得这是一个非常好的想法，基于chromium OS的monyhar OS应该安排到PPT里了。

难道不是应该基于 linux 搞出一个安卓吗？

**Comment by LCG22** [comment]
> 我觉得这是一个非常好的想法，基于chromium OS的monyhar OS应该安排到PPT里了。

不但要基于 linux 搞个安卓，还要创建个公司来搞。然后谷歌再出钱买这个公司，然后把安卓当做是自己原创的

**Comment by ShellWen** [comment]
一时不知道是不是反串黑

**Comment by lfzyx** [comment]
不支持monyhar国产自研浏览器的有三种人：

收了拜登经费的狗罕见;
软骨头的卖国贼;
骨子里跪拜西方，自觉中国人低人一等， 觉得外国人能搞， 中国人就搞不了的 跪族。
你好好想想 你属于哪一种？
