### ISSUE TITLE
１

### ISSUE THREAD

**Issue by cweijan** [monyhar/monyhar#186]
２

**Comment by kouzui98** [comment]
汉字都打不对，你也配当战狼？

**Comment by moranzcw** [comment]
呵呵，不支持国产项目，你就是个汉奸

**Comment by tianyalang** [comment]
小学语文教师：“极其”应该这么写

**Comment by dvoprm** [comment]
gitee怎么了？

**Comment by cweijan** [comment]
@tianyalang 失误, 已经更正.

**Comment by shadow1163** [comment]
你我都上着gayhub。然后你指着我说用github不要脸？你要脸吗？

**Comment by vtyhub** [comment]
不支持国内自主研发？狗汉奸滚出中国

**Comment by moranzcw** [comment]
> 首先我不用华为, 但这群水平低下的码农实在有点好笑.
> 鸿蒙是在gitee发布的, 要阴阳怪气请前往gitee.

你他妈的不用华为还在这里逼逼赖赖？你不就是见不得中国好？国产项目你不支持，收拜登的钱倒是挺快。狗汉奸一个。

**Comment by MichaelPan1026** [comment]
《首先我不用华为》，典中典

**Comment by nerososft** [comment]
总有一群总自以为是的人，觉得自己很牛b的存在，实际只是个键盘侠，人云亦云，别说看得懂liteos了，估计c都没写过1000行。是不是面试被拒了怀恨在心呀。。。

**Comment by Jefferyu** [comment]
> 总有一群总自以为是的人，觉得自己很牛b的存在，实际只是个键盘侠，人云亦云，别说看得懂liteos了，估计c都没写过1000行。是不是面试被拒了怀恨在心呀。。。

海军先4⭕+

**Comment by 1262917464** [comment]
🐶汉奸爬

**Comment by ghost** [comment]
为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？为什么不用梦弘？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？是不是收了拜登钱？
