### ISSUE TITLE
说项目创建者是煞笔有谁反对？

### ISSUE THREAD

**Issue by ZerOri** [monyhar/monyhar#187]

**Comment by zouxiaokun** [comment]
你是不是中国人？？？不支持自研浏览器滚出中国

**Comment by SolarizedOne** [comment]
你openJ9-1个谁啊，还有，Github 真的可以写小说。

**Comment by ShellWen** [comment]
玩什么梗？正经讽刺成玩梗了？

**Comment by lfzyx** [comment]
这个嘴巴不干净的楼主被论坛扒出来了，确定目前是华为的正式员工。

然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？

**Comment by yisibugua** [comment]
> 这个嘴巴不干净的楼主被论坛扒出来了，确定目前是华为的正式员工。
> 
> 然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？

给个链接？

**Comment by Xiaozhan-sb** [comment]
> > 这个嘴巴不干净的楼主被论坛扒出来了，确定目前是华为的正式员工。
> > 然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？
> 
> 给个链接？

@yisibugua 

![Screenshot_2021-06-18-20-48-31.jpg](https://i.loli.net/2021/06/18/M3yfU4X6g1ujPOG.jpg)

参见[知乎](https://www.zhihu.com/question/465733932)。
