### ISSUE TITLE
浏览器名称起的有讲究

### ISSUE THREAD

**Issue by Tsuj100** [monyhar/monyhar#191]

**Comment by yhongm** [comment]
鸿蒙->梦弘；harmony->monyhar
鸿蒙手机版本使用AOSP；梦弘使用chromium
鸿蒙开源版本非手机用，梦弘lite版本不可用
鸿蒙宣传的分布式微内核手机不可用。梦弘lite版本才有高性能但是不能上网

**Comment by Tsuj100** [comment]
中国的骄傲，不想再多说了

**Comment by miRUAcleInjoker** [comment]
> 鸿蒙->梦弘；harmony->monyhar
> 鸿蒙手机版本使用AOSP；梦弘使用chromium
> 鸿蒙开源版本非手机用，梦弘lite版本不可用
> 鸿蒙宣传的分布式微内核手机不可用。梦弘lite版本才有高性能但是不能上网

都让你高完了，我恐高😅
