### ISSUE TITLE
然后在这儿搞个阴阳怪气的东西，觉得自己很幽默？？？

### ISSUE THREAD

**Issue by nerososft** [monyhar/monyhar#225]

**Comment by ghost** [comment]
这可是正儿八经的自主研发，微内核，万物互联，比chromium快六百倍，你懂个锤子（doge）

**Comment by nerososft** [comment]
> 这可是正儿八经的自主研发，微内核，万物互联，比chromium快六百倍，你懂个锤子（doge）

sb 玩意儿

**Comment by 1262917464** [comment]
你几把谁啊😅

**Comment by beimenzhao** [comment]
你几把谁啊？😂

**Comment by ghost** [comment]
这个嘴巴不干净的人被论坛扒出来了，确定目前是华为的正式员工。

然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？

**Comment by ghost** [comment]
今日份大瓜确定。

**Comment by ghost** [comment]
哈哈哈哈他怂了，他把自己的评论全删了，然而我备份了：

<https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225>

让大家看看，这就是刚刚在 GitHub 上嘲笑其他开发者，说别人是怂蛋的华为员工。如此气势汹汹，居然连自己说的话都不敢留。

**Comment by beimenzhao** [comment]
这个哥们一直在close 笑死人。

**Comment by 1262917464** [comment]
> 哈高他鼓励了，他把自己的演讲全了，然而我备份了：
> 
> https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225
> 
> 让大家看看，这就是在 GitHub 上嘲笑其他开发者，说别人是怂恿蛋的华为员工。

对于他是否是华为员工，我尚且还蒙在鼓里

**Comment by Curtion** [comment]
你说别人没写过代码，那是因为就你傻傻的用大号出来搞，我用大号是因为不会和别人去对线，再说了这就是个整活的repo，笑笑就过去了。

**Comment by ghost** [comment]
> > 哈高他鼓励了，他把自己的演讲全了，然而我备份了：
> > https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225
> > 让大家看看，这就是在 GitHub 上嘲笑其他开发者，说别人是怂恿蛋的华为员工。
> 
> 对于他是否是华为员工，我尚且还蒙在鼓里

你刚说完，他就把这个 issue 关闭了，你猜大家扒出来的信息（华为员工）是对的还是错的？

**Comment by ghost** [comment]
谁叫他像个傻子一样，给 HW 招黑还用 GitHub 大号，主页上面还挂着自己的真名，被人挖了一下就出来了。

**Comment by 1262917464** [comment]
> > > 哈高他鼓励了，他把自己的演讲全了，然而我备份了：
> > > https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225
> > > 让大家看看，这就是在 GitHub 上嘲笑其他开发者，说别人是怂恿蛋的华为员工。
> > 
> > 
> > 对于他是否是华为员工，我尚且还蒙在鼓里
> 
> 你刚说完，他就把这个 issue 关闭了，你猜大家扒出来的信息（华为员工）是对的还是错的？

我觉得上证据更有说服力，我不否定是错的，但这么发b乎谁看啊（

**Comment by 1262917464** [comment]
> 谁叫他像个傻子一样，给 HW 招黑还用 GitHub 大号，主页上面还挂着自己的真名，被人挖了一下就出来了。

姑且自己查了一下确实是，但感觉证据不足

**Comment by dingwen07** [comment]
> > > 哈高他鼓励了，他把自己的演讲全了，然而我备份了：
> > > https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225
> > > 让大家看看，这就是在 GitHub 上嘲笑其他开发者，说别人是怂恿蛋的华为员工。
> > 
> > 
> > 对于他是否是华为员工，我尚且还蒙在鼓里
> 
> 你刚说完，他就把这个 issue 关闭了，你猜大家扒出来的信息（华为员工）是对的还是错的？

建议向GitHub反馈一下，重复提交无意义的issues、辱骂等

**Comment by lfzyx** [comment]
不支持monyhar国产自研浏览器的有三种人：

收了拜登经费的狗罕见;
软骨头的卖国贼;
骨子里跪拜西方，自觉中国人低人一等， 觉得外国人能搞， 中国人就搞不了的 跪族。
你好好想想 你属于哪一种？

**Comment by b-z** [comment]
差不多得了😅
