### ISSUE TITLE
一群正规代码没写过几行还自以为很牛逼的程序员自嗨？？？笑死。。。。

### ISSUE THREAD

**Issue by nerososft** [monyhar/monyhar#228]

**Comment by beimenzhao** [comment]
不支持monyhar国产自研浏览器的有三种人：
1.  收了拜登经费的狗罕见;
2. 软骨头的卖国贼;
3. 骨子里跪拜西方，自觉中国人低人一等， 觉得外国人能搞， 中国人就搞不了的  跪族。

你好好想想 你属于哪一种？

**Comment by nerososft** [comment]
> 不支持monyhar国产自研浏览器的有三种人：
> 
> 1. 收了拜登经费的狗罕见;
> 2. 软骨头的卖国贼;
> 3. 骨子里跪拜西方，自觉中国人低人一等， 觉得外国人能搞， 中国人就搞不了的  跪族。
> 
> 你好好想想 你属于哪一种？

我是你爸

**Comment by ghost** [comment]
这个嘴巴不干净的人被论坛扒出来了，确定目前是华为的正式员工。

然而他东家都不知道自己员工在 GitHub 上招黑。建议大家截图留存，顺便再去提个问题：如何看待某华为员工在 GitHub 上口吐脏言辱骂国产软件？

**Comment by ghost** [comment]
这可是个大瓜。

**Comment by ghost** [comment]
哈哈哈哈他怂了，他把自己的评论全删了，然而我备份了：

<https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225>

让大家看看，这就是刚刚在 GitHub 上嘲笑其他开发者，说别人是怂蛋的华为员工。如此气势汹汹，居然连自己说的话都不敢留。

**Comment by HaloWang** [comment]
秒啊~我瓜吃的停不下来

**Comment by Gua16** [comment]
这就是华为！

**Comment by ice1000** [comment]
> 哈哈哈哈他怂了，他把自己的评论全删了，然而我备份了：
> 
> https://web.archive.org/web/20210616134730/https://github.com/monyhar/monyhar/issues/225
> 
> 让大家看看，这就是刚刚在 GitHub 上嘲笑其他开发者，说别人是怂蛋的华为员工。如此气势汹汹，居然连自己说的话都不敢留。

就这点东西，求楼主的更多黑料，多来点🐶🤣
