### ISSUE TITLE
想必只会阴阳怪气的你也就只会在网络上自我安慰了吧😄

### ISSUE THREAD

**Issue by RealShiinaMashiro** [monyhar/monyhar#23]

**Comment by LittleVanPlus** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by XuanRanDev** [comment]
~~五十步笑百步~~

**Comment by kouzui98** [comment]
不会吧不会吧，花粉这就破防啦？

**Comment by Apatite0000** [comment]
这说明你不懂开源😅😅

**Comment by People-11** [comment]
把wawei做过的的事重复一遍就是阴阳怪气了是吧，那wawei可真厉害，阴阳怪气了一群海军呢😅😅😅

**Comment by gnaggnoyil** [comment]
海军您钩巴谁啊?😅

**Comment by yuchen001** [comment]
不会吧不会吧，还真有人被钓鱼了😅

**Comment by Decodetalkers** [comment]
这里面都是纯正的开发者

整这个活的人你可以去他主页看看，是活跃在rust社区的大佬，你算老几

**Comment by BlueSkyXN** [comment]
破防啦破防啦破防啦破防啦破防啦

**Comment by RESeiko** [comment]
建议去微博喷

**Comment by longalei** [comment]
它急啦

**Comment by SoyaLeaf** [comment]
> 想必只会阴阳怪气的你也就只会在网络上自我安慰了吧😄

在? 为什么要在issue里自我介绍?
还发这种非主流说说(说说...暴露年龄了2333).

**Comment by SnowyLake** [comment]
哇你这小号……

**Comment by Berial** [comment]
很难想象连github上都有分不清是非的人了

**Comment by Cathgao** [comment]
所以你何必在这里自我安慰呢？

**Comment by halo-shit** [comment]
滑伪是我爹，我不准你们骂它😅

**Comment by RealShiinaMashiro** [comment]
爷骂菊花的时候你还在玩小灵通😅

在 2021-06-19 00:20:21，hallo-shit ***@***.***> 写道：


滑伪是我爹，我不准你们骂它😅
