### ISSUE TITLE
什么牛鬼蛇神都出来带节奏么

### ISSUE THREAD

**Issue by MrFengHa** [monyhar/monyhar#263]

**Comment by MikiraSora** [comment]
你寄吧谁啊

**Comment by MrFengHa** [comment]
我是你爹啊

**Comment by Eazou** [comment]
你就是个见不得国产好，跪久了站不起来的狗汉奸！
努力了多久才出现一个梦弘，
国产浏览器苦 铬 久矣，
如今好不容易出来了完全原创的monyhar，你这种跪族就跑来带节奏，对得起你的国籍吗？

**Comment by MrFengHa** [comment]
？？？自己在这加挺多戏，我只是觉得你们没长脑子跟风。总是衣服众人皆醉我独醒。实则就是个脑子积水的大傻逼

**Comment by MrFengHa** [comment]
我还没说什么呢，你们这些恨国党就这疯。爱国怎么了，我草泥马的。怎么就不能爱国了。华为跟爱国有关系么，你大爷的。没长脑子的死玩意

**Comment by MrFengHa** [comment]
> 你就是个见不得国产好，跪久了站不起来的狗汉奸！
> 努力了多久才出现一个梦弘，
> 国产浏览器苦 铬 久矣，
> 如今好不容易出来了完全原创的monyhar，你这种跪族就跑来带节奏，对得起你的国籍吗？

**Comment by MrFengHa** [comment]
华为行不行不知道，我知道你们是真的垃圾

**Comment by Eazou** [comment]
狗汉奸原形毕露了吧，滚去美国吃瘦肉精，滚去日本吃核食吧
我们中国人，就是支持monyhar！

**Comment by MrFengHa** [comment]
狗儿子我是明白了，你们这哪是黑华为，你是在中国呀。你咋不去死呀，你怎么在你妈的子宫里没让羊水淹死啊

**Comment by x2031** [comment]
你寄吧谁啊🌊🌊🌊🌊🌊

**Comment by MrFengHa** [comment]
我是你爹 知道还问

**Comment by Pinky4000Plus** [comment]
总之小粉红40000+，其他随意

**Comment by MrFengHa** [comment]
我是你爹啊，知道你还问

**Comment by MrFengHa** [comment]
粉红怎了，一个有良知的人不爱自己国家，你在这装你妈

**Comment by ZhuoranLyu** [comment]
我寄吧谁啊，都寄吧谁啊

**Comment by ZhuoranLyu** [comment]
> 总之小粉红40000+，其他随意

不是40000+，是36000+

**Comment by MrFengHa** [comment]
一群傻逼

**Comment by Pinky4000Plus** [comment]
> 粉红怎了，一个有良知的人不爱自己国家，你在这装你妈

爱你赵爹的墙国是吧，狗还敢跑墙外来跳脸，你全家很难不死光。

**Comment by MrFengHa** [comment]
沙比的狗日儿子们  谁先死不好说  这是github
你们滚出github
github不被墙  沙比

**Comment by simonkimi** [comment]
是不是见不得国产的好?
