### ISSUE TITLE
建议采用额外附加模块的方式，在运行时对内存字符串进行全局替换

### ISSUE THREAD

**Issue by ghost** [monyhar/monyhar#266]
建议采用额外附加模块的方式，在运行时对内存字符串进行全局替换
这样不仅可以直接以二进制方式分发chrome，降低开发成本，实现解耦，减少编译时间，降低编译平台搭建成本，还能够在程序内实现对chrome的完全屏蔽，使得所有的chrome都变为monyhar。

**Comment by XJ-Zhang-Th** [comment]
一眼赢
