### ISSUE TITLE
适配了哄蒙操作系统吗？

### ISSUE THREAD

**Issue by xw-yin** [monyhar/monyhar#297]

**Comment by BHznJNs** [comment]
lite版本已经适配啦

**Comment by iMisty** [comment]
已经完美适配了homo系统啦

**Comment by LingyeSoul** [comment]
> _No description provided._

可以的
https://wwa.lanzoui.com/b0ewnzira 密码:3q3h
Monyhar梦弘浏览器 For Harmony Beta

注:这个软件只是一个玩笑，请勿当真！
PS:虽然是个玩笑，但其实完全可以正常使用
