### ISSUE TITLE
[数据删除]

### ISSUE THREAD

**Issue by RimuruChan** [monyhar/monyhar#356]

**Comment by RimuruChan** [comment]
![{ N9{~%(DYKDKHTB LPV@L](https://user-images.githubusercontent.com/42002296/122746856-046f7f80-d2bd-11eb-8f21-12b3f84a2b34.jpg)

**Comment by gqduke** [comment]
差不多得了

**Comment by RimuruChan** [comment]
> 差不多得了

分不清大是大非吗，这是国产浏览器，必须要支持

**Comment by memeteli** [comment]
別逼人家，越逼越讓人煩

**Comment by layue13** [comment]
@RimuruChan Github警察
![}$ 6T_M@9U5OL` V BR)~RJ](https://user-images.githubusercontent.com/54186311/123030508-81157180-d415-11eb-8fc5-06f33cf75add.gif)

**Comment by memeteli** [comment]
> @RimuruChan Github警察
> ![}$ 6T_M@9U5OL` V BR)~RJ](https://user-images.githubusercontent.com/54186311/123030508-81157180-d415-11eb-8fc5-06f33cf75add.gif)

趕緊報警！

**Comment by zjw-swun** [comment]
你可以不用国产浏览器，但是看见它一定要鞠躬

**Comment by memeteli** [comment]
什麽年代了，還要分國產非國產，哪個質量好，就用哪個。
