### ISSUE TITLE
3个月没更新了 作者放弃了吗

### ISSUE THREAD

**Issue by HuRuWo** [monyhar/monyhar#416]
我看原仓库 chromium 还在保持更新，请拉一下最新代码
可惜了这么好的国产软件就停更了
可以发起一个众筹 让大家一起建设生态

**Comment by Iridescentangle** [comment]
这位群众对于米帝国主义的狼子野心还是低估了.

当我们试图研发一款自主知识产权浏览器时,就意味着我们站起来了,从此不会再被米国企业卡脖子了,他们当然怕得要死,他们不会允许我们和他们平起平坐的.

所以对应地,他们会封锁和卡脖子,表现为:即使是开源的项目,也不给我们用,不信你试试,从chromium直接拉代码,会因为各种原因最终失败.

邪恶的帝国主义就是通过这种方式来阻止我们的技术进步.所以不要妄想帝国主义会开恩放弃卡脖子了.

**他们开源项目更新,但是他们卡脖子,这就是我们必须自主研发的理由!**


手动狗头
