### ISSUE TITLE
这里真的是程序员吗？程序员社区不过如此

### ISSUE THREAD

**Issue by Zeroand-one** [monyhar/monyhar#428]
看来微博不是粪坑，而是聚集了大量的人

**Comment by x2031** [comment]
你鸡巴谁啊🤨

**Comment by halo-shit** [comment]
你妈是批发的么？这么能送

**Comment by x2031** [comment]
> 你妈是批发的么？这么能送

所以你几把又是谁啊😶

**Comment by halo-shit** [comment]
> > 你妈是批发的么？这么能送
> 
> 所以你几把又是谁啊no_mouth

nmd，我是友军啊，我说的是发issue这个吊毛
