### ISSUE TITLE
笑死，这不就是鸿蒙现状

### ISSUE THREAD

**Issue by DanKE123abc** [monyhar/monyhar#433]

**Comment by yyqwe158** [comment]
像这个monyhar
在某些程度上就比鸿蒙好
手机鸿蒙还不肯开源
好歹开源个没有hms的版本啊
单靠说与宣传能封得了反对者的嘴？
真把人当傻子了？
你一开源，黑子立马没90%

更何况，你不开源，除了自家手机，谁会用？作为一个新生的系统，应尽可能地为自己未来的发展立好脚步。起步比ios，安卓晚，生态又比不过ios跟安卓。
我们日常生活用的软件，qq，微信，有几个鸿蒙特供版？
最好搞到最后不要是浏览器套壳。

之前的红芯浏览器已经开了个坏头了
大家不是不支持国产
只是不想被当成沙比

说到底
用开源的东西又不会怎么样，像谁骂统信，麒麟了？像这样遮遮掩掩有什么用？

希望手机鸿蒙最好自己能整出个好成绩
而不是靠着新闻媒体和水军给你整
