### ISSUE TITLE
建议搭配Anti 996 License 使用！

### ISSUE THREAD

**Issue by ykla** [monyhar/monyhar#53]
见https://github.com/996icu/996.ICU/blob/master/LICENSE

**Comment by AlpacaBi** [comment]
我感觉可以弄一个support 996的License出来

**Comment by ouuan** [comment]
Anti 996 不是开源许可证，应该使用完全自主研发，经过 OSI 认证的 https://license.coscl.org.cn/MulanPSL2/

**Comment by ykla** [comment]
> 我感觉可以弄一个support 996的License出来

感觉可以有！

**Comment by SekiBetu** [comment]
+1
