### ISSUE TITLE
issue里有很多反动言论了，公然对抗中国共产党的领导。好自为之吧

### ISSUE THREAD

**Issue by liaoweijun** [monyhar/monyhar#68]

**Comment by Xiaozhan-sb** [comment]
给你加个🐶

**Comment by xuke-hat** [comment]
早该管管了！

**Comment by Feng-Bu-Jue** [comment]
流汗黄豆

**Comment by dontpanic92** [comment]
如果有，请指出。我会做屏蔽和删除处理。

**Comment by Bob-Bush102** [comment]
> 如果有，请指出。我会做屏蔽和删除处理。
Accelerate下面有部分链接。发表64相关言论

**Comment by Bob-Bush102** [comment]
> 如果有，请指出。我会做屏蔽和删除处理。

以及Accelerate!Accelerate! #57中

**Comment by dontpanic92** [comment]
#67 里的链接做了屏蔽处理。#57 属于泄露个人隐私，已删除。

**Comment by TooYoungTooSimp** [comment]
别的不说你发那么多名字超长的issue是不是被吓得过头了。。。。。

**Comment by lolisix** [comment]
> 如果有，请指出。我会做屏蔽和删除处理。

#33 的一个网址

**Comment by dontpanic92** [comment]
> > 如果有，请指出。我会做屏蔽和删除处理。
> 
> #33 的一个网址

Done. （有点奇怪这不就是楼主吗…

**Comment by LisPerfect** [comment]
不都是你个不支持国产浏览器的勾罕见车的？
